fixtures:
  repositories:
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "inifile": "git://github.com/cprice-puppet/puppetlabs-inifile"
    "mysql": "git://github.com/puppetlabs/puppetlabs-mysql.git"
  symlinks:
    "ceilometer": "#{source_dir}"
