fixtures:
  repositories:
    'inifile': 'git://github.com/puppetlabs/puppetlabs-inifile'
    'keystone': 'git://github.com/stackforge/puppet-keystone.git'
    'mysql': 'git://github.com/puppetlabs/puppetlabs-mysql.git'
    'nova': 'git://github.com/stackforge/puppet-nova.git'
    'openstacklib': 'git://github.com/stackforge/puppet-openstacklib.git'
    'stdlib': 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
  symlinks:
    'ceilometer': "#{source_dir}"
